# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)


#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development: &development
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: SCUF_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: SCUF_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *development

